
import pytest
from code_writer_usecase.functions import calculate_rectangle_area


def test_calculate_rectangle_area():
    """
    This unit test function was generated by Mixtral with the specification of the unit test and the function to tset in input.
    """
    # Test Case 1: Calculate area for a rectangle with positive length and width.
    length = 5.0
    width = 3.0
    expected_output = length * width
    result = calculate_rectangle_area(length, width)
    assert result == expected_output

    # Test Case 2: Test for invalid input (negative length).
    length = -5.0
    width = 3.0
    with pytest.raises(ValueError):
        calculate_rectangle_area(length, width)

    # Test Case 3: Test for invalid input (zero width).
    length = 5.0
    width = 0.0
    with pytest.raises(ValueError):
        calculate_rectangle_area(length, width)

    # Test Case 4: Test for invalid input (non-numeric length).
    length = "a"
    width = 3.0
    with pytest.raises(ValueError):
        calculate_rectangle_area(length, width)

    # Test Case 5: Test for invalid input (non-numeric width).
    length = 5.0
    width = "b"
    with pytest.raises(ValueError):
        calculate_rectangle_area(length, width)


retcode = pytest.main(["-x", "D:\\TSP\\TSP_3A\\projet_AI\\projet_ia_telecom\\backend\\code_writer_usecase"])
# The code written by the AI pass sucessfully